version: "3"
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: realworld-docker-frontend
    command: serve -s build -l 3000
    ports:
     - "3000:3000"
    restart: unless-stopped
    stdin_open: true
    tty: true 
  api:
    build: .
    command: npm run start
    ports:
      - "80:8080"
    environment: 
      - PORT=8080
      - HOST=http://shevchuk-lab4-docker.com
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db
  api_db:
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db
volumes:
  mongodb_api: