version: "3"
services: 
  api:
    build: .
    command: npm run dev
    volumes:
      - ./api/src:/usr/src/app/src
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: realworld-docker-frontend
    command: npm start
    ports:
     - "3000:3000"
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment: 
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - './frontend:/usr/src/app'
      - '/app/node_modules'