version: "3"
services: 
  api:
    build: .
    command: npm run start
    ports:
      - "80:8080"
    environment: 
      - PORT=8080
      - HOST=http://shevchuk-lab4-docker.com
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db
  api_db:
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db
volumes:
  mongodb_api: